// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuSrrxhZLHGnIe1URd8GnbvtaJ6eV8KQ',
    appId: '1:88145088404:android:4a86b4d66870ff925e4981',
    messagingSenderId: '88145088404',
    projectId: 'online-auction-system-2e40c',
    storageBucket: 'online-auction-system-2e40c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQLun0Fea7s5IfzW4uuWVPHm7zY8H-iE',
    appId: '1:88145088404:ios:079436d9c50839715e4981',
    messagingSenderId: '88145088404',
    projectId: 'online-auction-system-2e40c',
    storageBucket: 'online-auction-system-2e40c.appspot.com',
    iosBundleId: 'com.example.calisma3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQWdwm-vS3_5pdTOasDbNovI4ypDXba-g',
    appId: '1:88145088404:web:26efda1af8b98e7c5e4981',
    messagingSenderId: '88145088404',
    projectId: 'online-auction-system-2e40c',
    authDomain: 'online-auction-system-2e40c.firebaseapp.com',
    storageBucket: 'online-auction-system-2e40c.appspot.com',
    measurementId: 'G-0E2B4H4DNQ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWdwm-vS3_5pdTOasDbNovI4ypDXba-g',
    appId: '1:88145088404:web:f966c2d0892ffdc25e4981',
    messagingSenderId: '88145088404',
    projectId: 'online-auction-system-2e40c',
    authDomain: 'online-auction-system-2e40c.firebaseapp.com',
    storageBucket: 'online-auction-system-2e40c.appspot.com',
    measurementId: 'G-6RDDXXVW5B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQLun0Fea7s5IfzW4uuWVPHm7zY8H-iE',
    appId: '1:88145088404:ios:079436d9c50839715e4981',
    messagingSenderId: '88145088404',
    projectId: 'online-auction-system-2e40c',
    storageBucket: 'online-auction-system-2e40c.appspot.com',
    iosBundleId: 'com.example.calisma3',
  );

}